eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 35 #укажите интервал в 35 сек через который клиент шлет эхо запрос на сервер
    instance:
      preferIpAddress: true #использовать IP адрес